---

- hosts: all

  sudo: yes

  tasks:

    - name: make sure required packages are installed
      apt: pkg=nginx,git,python3,python3-pip state=present update_cache=yes

    - name: make sure virtualenv is installed
      command: pip3 install virtualenv

    - name: allow long hostnames in nginx
      lineinfile:
        dest=/etc/nginx/nginx.conf
        regexp='(\s+)#? ?server_names_hash_bucket_size'
        backrefs=yes
        line='\1server_names_hash_bucket_size 64;'
    - name: add nginx config to sites-available
      template: src=./nginx.conf.j2
                dest=/etc/nginx/sites-available/{{ inventory_hostname }}

    - name: add symlink in nginx sites-enabled
      file: src=/etc/nginx/sites-available/{{ inventory_hostname }}
            dest=/etc/nginx/sites-enabled/{{ inventory_hostname }} state=link

    - name: disable default nginx page
      file: path=/etc/nginx/sites-enabled/default
            state=absent

    - name: write gunicorn init script
      template: src=./gunicorn-upstart.conf.j2
                dest=/etc/init/gunicorn-{{ inventory_hostname }}.conf

...
